from __future__ import annotations

from datetime import datetime, timedelta
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from tsundoku.models.tasks import Ingestion, Task, Event

from tsundoku.models import settings

import json
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from groq import Groq, AuthenticationError


def _organizeViaProxy(rawText: str, proxyUrl: str) -> OrganizeResult:
    request = Request(
        proxyUrl,
        data=json.dumps({"text": rawText}).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=35) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except HTTPError as error:
        try:
            payload = json.loads(error.read().decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            payload = {}
        if error.code == 429:
            message = payload.get("error") or "Demo usage limit reached. Please try again later."
            raise RuntimeError(message) from error
        raise RuntimeError("The demo organizer is temporarily unavailable. Please try again later.") from error
    except (URLError, TimeoutError, ValueError) as error:
        raise RuntimeError("Couldn't reach the demo organizer. Please try again.") from error

    if not isinstance(payload, dict) or "tasks" not in payload or "events" not in payload:
        raise RuntimeError("The demo organizer returned an invalid response. Please try again.")
    return OrganizeResult.model_validate(payload)

class TaskDraft(BaseModel):
    title: str
    description: str = ""
    scheduledStart: datetime |None = None
    isAllDay: bool = False
    deadline: datetime | None = None
    durationMinutes: int | None = Field(default=None, ge=1)
    priority: str = "normal"
    parentRef: str | None = Field(
        default=None,
        description="Title of parent goal when this row is a session/subtask.",
    )
    eventRef: str | None = Field(
        default=None,
        description="Title of the event this task prepares for, when applicable.",
    )

class EventDraft(BaseModel):
    title: str
    description: str = ""
    scheduledStart: datetime | None = None
    isAllDay: bool = False


class OrganizeResult(BaseModel):
    tasks: list[TaskDraft] = Field(default_factory=list)
    message: str | None = None
    events: list[EventDraft] = Field(default_factory=list)


systemPrompt = """Extract actionable tasks from the user's message.

Reference time: {referenceTime}

Rules:
- Extract events and actionable tasks from the user's message.
- No actionable intent, event, or insufficient information → return events=[] and tasks=[] with a brief helpful message.
- Never invent events or tasks.
- Preserve unknown fields as null or sensible defaults.
- Resolve relative dates using the reference time.

Events:
- An event is a notable occurrence that happens at a particular date or time.
- Examples include tests, exams, appointments, presentations, concerts, and similar occurrences.
- An event is NOT an action the user needs to perform.
- If the user describes a notable upcoming occurrence, create an event.
- An event may have preparation tasks associated with it.
- If the user explicitly mentions work they need to do to prepare for an event, create tasks for that work.
- Do not create a task for the event itself.
- event scheduledStart is when the event occurs.
- Events do not have duration, priority, deadline, or parentID fields.

Tasks:
- A task is an action the user needs to perform.
- deadline: ISO 8601 datetime or null.
- durationMinutes: realistic estimate, usually 45–120, or null.
- priority: low, normal, or high.
- parentRef: title of another task when this task is a subtask or preparation task belonging to that task.
- eventRef: title of the event this task prepares for, or null when unrelated to an event.
- eventID is not provided by the user or generated by the LLM. The application assigns eventID after the event and its tasks are created.

For each task:
- scheduledStart is the intended start date and time for doing the task.
- deadline is the latest date and time by which the task should be completed.
- If the user explicitly gives a time for doing the task, put it in scheduledStart.
- Do not put an explicit task start time into deadline.
- Only use deadline when the user expresses a deadline, due date, or latest completion time.
- If neither is specified, use null.

For task scheduledStart and isAllDay:
- If the user gives a specific date AND time, set scheduledStart to that datetime and isAllDay to false.
- If the user gives a date but NO time, set scheduledStart to that date at midnight and isAllDay to true.
- If the user gives no date, set scheduledStart to null and isAllDay to false.
- isAllDay means the task should appear as a full-day calendar item.

For event scheduledStart and isAllDay:
- If the user gives a specific date AND time for the event, set scheduledStart to that datetime and isAllDay to false.
- If the user gives a date but NO time, set scheduledStart to that date at midnight and isAllDay to true.
- If the user gives no date, set scheduledStart to null and isAllDay to false.
- isAllDay means the event should appear as a full-day calendar item.
"""

def fallbackOrganize(rawText: str) -> OrganizeResult:
    return OrganizeResult(
        tasks=[
            TaskDraft(
                title=rawText[:200],
                description=rawText if len(rawText) > 200 else "",
            )
        ]
    )

def organizeWithLlm(rawText: str, client=None) -> OrganizeResult:
    if client is None:
        proxyUrl = settings.loadAiProxyUrl()
        if proxyUrl:
            try:
                return _organizeViaProxy(rawText, proxyUrl)
            except Exception as error:
                return OrganizeResult(tasks=[], events=[], message=str(error))

    try:
        if client is None:
            apiKey = settings.loadApi()
            if not apiKey:
                return OrganizeResult(
                    tasks=[],
                    message="The AI demo is not configured yet. Ask the app maintainer to finish setup."
                )
            client = Groq(api_key=apiKey)

        completion = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            messages=[
                {
                    "role": "system",
                    "content": systemPrompt.replace(
                        "{referenceTime}", datetime.now().astimezone().isoformat()
                    ),
                },
                {"role": "user", "content": rawText},
            ],
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "organize_result",
                    "schema": OrganizeResult.model_json_schema(),
                },
            },
        )
    except AuthenticationError:
        return OrganizeResult(
            tasks=[],
            message="There was a problem connecting to Groq. Check your API key and try again."
        )
    except Exception:
        return OrganizeResult(
            tasks=[], events=[],
            message="Couldn't reach the organizer service or read its response. Please try again.",
        )

    try:
        content = completion.choices[0].message.content
        if not content:
            return fallbackOrganize(rawText)
        return OrganizeResult.model_validate(json.loads(content))
    except Exception:
        return OrganizeResult(
            tasks=[], events=[],
            message="The organizer returned an invalid response. Please try again.",
        )

def applyOrganizeResult(
    result: OrganizeResult,
    rawText: str,
    ingestionID: UUID | None = None,
) -> tuple[Ingestion, list[Event], list[Task]]:
    """Map LLM output to domain objects with stable IDs and relationships."""

    ingestion = Ingestion(
        id=ingestionID or uuid4(),
        rawText=rawText,
        timeStamp=datetime.now().astimezone(),
    )

    events: list[Event] = []
    tasks: list[Task] = []

    for eventDraft in result.events:
        event = Event(
            id=uuid4(),
            title=eventDraft.title,
            description=eventDraft.description,
            scheduledStart=eventDraft.scheduledStart,
            isAllDay=eventDraft.isAllDay,
            ingestionID=ingestion.id,
        )

        events.append(event)

    titleToEventId = {event.title: event.id for event in events}

    titleToId: dict[str, UUID] = {}

    for draft in result.tasks:
        taskId = uuid4()
        titleToId[draft.title] = taskId

        duration = (
            timedelta(minutes=draft.durationMinutes)
            if draft.durationMinutes is not None
            else None
        )

        tasks.append(
            Task(
                id=taskId,
                title=draft.title,
                description=draft.description,
                scheduledStart=draft.scheduledStart,
                deadline=draft.deadline,
                duration=duration,
                priority=draft.priority,
                completed=False,
                parentID=None,
                eventID=titleToEventId.get(draft.eventRef)
                if draft.eventRef
                else (events[0].id if len(events) == 1 else None),
                ingestionID=ingestion.id,
                isAllDay=draft.isAllDay,
            )
        )

    for draft, task in zip(result.tasks, tasks, strict=True):
        if not draft.parentRef:
            continue

        parentId = titleToId.get(draft.parentRef)

        if parentId is not None:
            task.parentID = parentId

    return ingestion, events, tasks
